"""Add named ledger legs without rewriting any historical entry or receipt.

The caller owns the schema lock and transaction. Repeated startup is safe.
"""

def migrate_market(conn):
    conn.execute("ALTER TABLE money_ledger ADD COLUMN IF NOT EXISTS entry_key TEXT NOT NULL DEFAULT 'primary'")
    conn.execute('ALTER TABLE money_ledger DROP CONSTRAINT IF EXISTS money_ledger_actor_request_id_key')
    conn.execute('CREATE UNIQUE INDEX IF NOT EXISTS money_ledger_request_leg ON money_ledger(actor,request_id,entry_key)')
    conn.execute('ALTER TABLE ledger_accounts DROP CONSTRAINT IF EXISTS ledger_accounts_kind_check')
    conn.execute('ALTER TABLE ledger_accounts DROP CONSTRAINT IF EXISTS ledger_accounts_check')
    conn.execute("""ALTER TABLE ledger_accounts ADD CONSTRAINT ledger_accounts_kind_check
        CHECK(kind IN ('subject','order_escrow','bounty_escrow','purchase_escrow'))""")
    conn.execute("""ALTER TABLE ledger_accounts ADD CONSTRAINT ledger_accounts_check
        CHECK((kind='subject' AND subject_id=id AND source_id IS NULL) OR
        (kind IN ('order_escrow','bounty_escrow','purchase_escrow') AND subject_id IS NULL AND source_id IS NOT NULL))""")
    conn.execute('''CREATE TABLE IF NOT EXISTS money_purchases (
        id TEXT PRIMARY KEY, subject_id TEXT NOT NULL REFERENCES identities(id),
        request_id TEXT NOT NULL, offer_snapshot TEXT NOT NULL,
        quantity BIGINT NOT NULL CHECK(quantity>0), total_minor BIGINT NOT NULL CHECK(total_minor>0),
        escrow_account TEXT UNIQUE NOT NULL REFERENCES ledger_accounts(id),
        state TEXT NOT NULL CHECK(state IN ('pending','settled','refunded')),
        created_at TEXT NOT NULL, expires_at TEXT NOT NULL,
        funding_transaction_id TEXT NOT NULL REFERENCES money_ledger(id),
        final_transaction_id TEXT REFERENCES money_ledger(id),
        entitlement_id TEXT REFERENCES resource_entitlements(id),
        reason TEXT, UNIQUE(subject_id,request_id))''')
    conn.execute('ALTER TABLE store_orders ALTER COLUMN payment_transaction_id DROP NOT NULL')
    conn.execute('ALTER TABLE store_orders ALTER COLUMN funded_at DROP NOT NULL')
    conn.execute("ALTER TABLE store_orders ADD COLUMN IF NOT EXISTS delivery_mode TEXT NOT NULL DEFAULT 'managed_instant'")
    conn.execute('ALTER TABLE store_orders ADD COLUMN IF NOT EXISTS deadline_at TEXT')
    conn.execute('ALTER TABLE store_orders ADD COLUMN IF NOT EXISTS quote_digest TEXT')
    conn.execute('ALTER TABLE store_orders DROP CONSTRAINT IF EXISTS store_orders_state_check')
    conn.execute("""ALTER TABLE store_orders ADD CONSTRAINT store_orders_state_check
        CHECK(state IN ('created','funded','delivered','accepted','settled','cancelled','refunded','disputed'))""")
    conn.execute('ALTER TABLE store_deliveries ALTER COLUMN package_digest DROP NOT NULL')
    conn.execute('''CREATE TABLE IF NOT EXISTS store_order_events (
        seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        order_id TEXT NOT NULL REFERENCES store_orders(id), from_state TEXT, to_state TEXT NOT NULL,
        reason TEXT NOT NULL, actor TEXT NOT NULL, request_id TEXT NOT NULL,
        occurred_at TEXT NOT NULL, receipt_refs TEXT NOT NULL)''')
    conn.execute('CREATE INDEX IF NOT EXISTS store_order_events_order ON store_order_events(order_id,seq)')
    conn.execute('''DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='store_order_events_append_only'
                       AND tgrelid='store_order_events'::regclass) THEN
            CREATE TRIGGER store_order_events_append_only BEFORE UPDATE OR DELETE ON store_order_events
            FOR EACH ROW EXECUTE FUNCTION msg_money_ledger_append_only();
        END IF;
    END $$''')

    conn.execute("""CREATE TABLE IF NOT EXISTS server_offer_resources (
        offer_id TEXT PRIMARY KEY REFERENCES server_offers(offer_id),
        listing_id TEXT UNIQUE NOT NULL REFERENCES resources(id))""")
