"""PostgreSQL metadata store with the same transactional session contract as SQLite.

All writes take one transaction-scoped advisory lock. The existing executor relies on
SQLite's BEGIN IMMEDIATE serialization for request replay, audit chaining and job
deduplication; this lock preserves that ordering across processes and hosts.
"""
from __future__ import annotations

import asyncio
import contextvars
import logging
import os
import re
import subprocess
import uuid
from contextlib import asynccontextmanager
from pathlib import Path

import psycopg
from psycopg.conninfo import conninfo_to_dict, make_conninfo

from msg.core.errors import Failure
from msg.storage.sqlite import SqliteSession

_SCHEMA = """
CREATE TABLE IF NOT EXISTS schema_version (version INTEGER PRIMARY KEY);
INSERT INTO schema_version (version) VALUES (1) ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS resources (
 id TEXT PRIMARY KEY, type TEXT NOT NULL, name TEXT NOT NULL,
 parent TEXT REFERENCES resources(id) DEFERRABLE INITIALLY DEFERRED,
 owner TEXT NOT NULL, grp TEXT NOT NULL, mode INTEGER NOT NULL,
 generation INTEGER NOT NULL, revision TEXT, state TEXT NOT NULL,
 created_at TEXT NOT NULL, modified_at TEXT NOT NULL, body TEXT NOT NULL,
 UNIQUE(parent,name));
CREATE UNIQUE INDEX IF NOT EXISTS one_root ON resources((1)) WHERE parent IS NULL;
CREATE INDEX IF NOT EXISTS resources_parent ON resources(parent,id);
CREATE INDEX IF NOT EXISTS resources_time ON resources(created_at,id);
CREATE INDEX IF NOT EXISTS resources_owner ON resources(owner,id);
CREATE TABLE IF NOT EXISTS resource_tags (
 resource_id TEXT NOT NULL REFERENCES resources(id) ON DELETE CASCADE,
 tag TEXT NOT NULL, PRIMARY KEY(tag,resource_id));
CREATE INDEX IF NOT EXISTS resource_tags_resource ON resource_tags(resource_id);
CREATE TABLE IF NOT EXISTS revisions (
 id TEXT PRIMARY KEY, resource_id TEXT NOT NULL REFERENCES resources(id),
 created_at TEXT NOT NULL, body TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS revisions_resource ON revisions(resource_id,created_at,id);
CREATE TABLE IF NOT EXISTS relations (
 revision_id TEXT NOT NULL REFERENCES revisions(id) ON DELETE CASCADE,
 source_id TEXT NOT NULL, type TEXT NOT NULL, target_id TEXT NOT NULL,
 target_revision TEXT, body TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS relations_target ON relations(target_id,type);
CREATE TABLE IF NOT EXISTS identities (id TEXT PRIMARY KEY, kind TEXT NOT NULL, generation INTEGER NOT NULL, body TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS memberships (org TEXT, subject TEXT, generation INTEGER NOT NULL, body TEXT NOT NULL, PRIMARY KEY(org,subject));
CREATE TABLE IF NOT EXISTS emails (subject TEXT PRIMARY KEY, generation INTEGER NOT NULL, body TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS credentials (id TEXT PRIMARY KEY, subject TEXT NOT NULL, body TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS credentials_subject ON credentials(subject);
CREATE TABLE IF NOT EXISTS identity_keys (
 key_id TEXT PRIMARY KEY, subject TEXT NOT NULL, public_key TEXT NOT NULL,
 created_at TEXT NOT NULL, retired_at TEXT, is_primary INTEGER NOT NULL DEFAULT 0);
CREATE UNIQUE INDEX IF NOT EXISTS identity_keys_primary ON identity_keys(subject) WHERE is_primary=1;
CREATE INDEX IF NOT EXISTS identity_keys_subject ON identity_keys(subject,created_at,key_id);
CREATE TABLE IF NOT EXISTS encryption_subkeys (
 key_id TEXT PRIMARY KEY, subject TEXT NOT NULL, recipient TEXT NOT NULL UNIQUE,
 public_key TEXT NOT NULL, created_at TEXT NOT NULL, retired_at TEXT,
 is_primary INTEGER NOT NULL DEFAULT 0);
CREATE UNIQUE INDEX IF NOT EXISTS encryption_subkeys_primary ON encryption_subkeys(subject) WHERE is_primary=1;
CREATE INDEX IF NOT EXISTS encryption_subkeys_subject ON encryption_subkeys(subject,created_at,key_id);
CREATE TABLE IF NOT EXISTS certificates (id TEXT PRIMARY KEY, subject TEXT NOT NULL, parent TEXT, revoked INTEGER NOT NULL DEFAULT 0, body TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS csrs (id TEXT PRIMARY KEY, generation INTEGER NOT NULL, state TEXT NOT NULL, body TEXT NOT NULL, state_body TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS results (subject TEXT, request_id TEXT, digest TEXT NOT NULL, body TEXT NOT NULL, PRIMARY KEY(subject,request_id));
CREATE TABLE IF NOT EXISTS batches (subject TEXT, request_id TEXT, digest TEXT NOT NULL, PRIMARY KEY(subject,request_id));
CREATE TABLE IF NOT EXISTS transfers (id TEXT PRIMARY KEY, subject TEXT NOT NULL, generation INTEGER NOT NULL, body TEXT NOT NULL, limits TEXT NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS chunks (transfer_id TEXT NOT NULL, "offset" BIGINT NOT NULL, length BIGINT NOT NULL, body TEXT NOT NULL, PRIMARY KEY(transfer_id,"offset"));
CREATE TABLE IF NOT EXISTS events (seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id TEXT UNIQUE NOT NULL, body TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS audit (seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, digest TEXT UNIQUE NOT NULL, previous TEXT, body TEXT NOT NULL);
CREATE OR REPLACE FUNCTION msg_audit_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'append_only_audit' USING ERRCODE = '23514'; END;
$$;
DO $$ BEGIN
 IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'audit_no_update'
                AND tgrelid = 'audit'::regclass) THEN
  CREATE TRIGGER audit_no_update BEFORE UPDATE OR DELETE ON audit
   FOR EACH ROW EXECUTE FUNCTION msg_audit_append_only();
 END IF;
END $$;
CREATE TABLE IF NOT EXISTS jobs (id TEXT PRIMARY KEY, dedupe TEXT UNIQUE NOT NULL, kind TEXT NOT NULL, state TEXT NOT NULL, next_at TEXT NOT NULL, body TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS watches (subject TEXT, resource TEXT, PRIMARY KEY(subject,resource));
CREATE TABLE IF NOT EXISTS messages (id TEXT PRIMARY KEY, sender TEXT, recipient TEXT, resource TEXT, event_id TEXT, body TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS reactions (subject TEXT, resource TEXT, kind TEXT, revision TEXT NOT NULL DEFAULT '', body TEXT NOT NULL, PRIMARY KEY(subject,resource,kind,revision));
CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS projections (resource_id TEXT PRIMARY KEY, text TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS email_challenges (subject TEXT PRIMARY KEY, digest TEXT NOT NULL, expires TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS achievement_ceremonies (
 id TEXT PRIMARY KEY, subject TEXT NOT NULL, state TEXT NOT NULL, body TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS achievement_ceremonies_subject ON achievement_ceremonies(subject);
CREATE TABLE IF NOT EXISTS achievement_grants (
 id TEXT PRIMARY KEY, subject TEXT NOT NULL, achievement_id TEXT NOT NULL,
 spec_version INTEGER NOT NULL, body TEXT NOT NULL,
 UNIQUE(subject,achievement_id,spec_version));
CREATE INDEX IF NOT EXISTS achievement_grants_lookup ON achievement_grants(achievement_id,subject);
CREATE TABLE IF NOT EXISTS dm_conversations (
 pair TEXT PRIMARY KEY, resource_id TEXT NOT NULL UNIQUE REFERENCES resources(id),
 participant_a TEXT NOT NULL, participant_b TEXT NOT NULL, initiator TEXT NOT NULL,
 conversation_kind TEXT NOT NULL DEFAULT 'direct' CHECK(conversation_kind='direct'),
 state TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL,
 CHECK(participant_a < participant_b), CHECK(state IN ('pending','active','rejected')));
CREATE INDEX IF NOT EXISTS dm_conversations_participants ON dm_conversations(participant_a,participant_b);
CREATE TABLE IF NOT EXISTS dm_blocks (
 blocker TEXT NOT NULL, blocked TEXT NOT NULL, PRIMARY KEY(blocker,blocked));
CREATE TABLE IF NOT EXISTS dm_archives (
 subject TEXT NOT NULL, pair TEXT NOT NULL REFERENCES dm_conversations(pair),
 PRIMARY KEY(subject,pair));
CREATE TABLE IF NOT EXISTS presence (
 subject TEXT PRIMARY KEY, expires_at TEXT NOT NULL, body TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS claims (
 id TEXT PRIMARY KEY REFERENCES resources(id), subject TEXT NOT NULL,
 issued_at TEXT NOT NULL, expires_at TEXT, body TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS claims_subject ON claims(subject,issued_at,id);
CREATE TABLE IF NOT EXISTS topic_settings (
 topic TEXT PRIMARY KEY REFERENCES resources(id), membership_policy TEXT NOT NULL,
 CHECK(membership_policy IN ('open','approval','invite','closed')));
CREATE TABLE IF NOT EXISTS topic_memberships (
 topic TEXT NOT NULL REFERENCES resources(id), subject TEXT NOT NULL,
 role TEXT NOT NULL CHECK(role IN ('admin','member')),
 status TEXT NOT NULL CHECK(status IN ('active','pending','invited','left','removed')),
 joined_at TEXT, invited_by TEXT, PRIMARY KEY(topic,subject));
CREATE INDEX IF NOT EXISTS topic_memberships_subject ON topic_memberships(subject,topic);
CREATE TABLE IF NOT EXISTS topic_bans (
 topic TEXT NOT NULL REFERENCES resources(id), subject TEXT NOT NULL,
 actor TEXT NOT NULL, created_at TEXT NOT NULL, expires_at TEXT, reason TEXT,
 status TEXT NOT NULL CHECK(status IN ('active','lifted')),
 PRIMARY KEY(topic,subject));
CREATE TABLE IF NOT EXISTS system_sources (
 resource_id TEXT PRIMARY KEY REFERENCES resources(id), source_path TEXT NOT NULL UNIQUE,
 rule_id TEXT NOT NULL UNIQUE, source_kind TEXT NOT NULL,
 source_version INTEGER NOT NULL, source_digest TEXT NOT NULL,
 revision_id TEXT NOT NULL REFERENCES revisions(id));
CREATE TABLE IF NOT EXISTS personal_revision_proofs (
 revision_id TEXT PRIMARY KEY REFERENCES revisions(id), subject TEXT NOT NULL,
 kind TEXT NOT NULL, signature TEXT NOT NULL, signed_envelope TEXT NOT NULL,
 created_at TEXT NOT NULL);
"""


def _postgres_sql(sql: str, *, has_parameters: bool = False) -> str:
    """Translate shared SQLite SQL without altering quoted text or comments."""
    ignore = re.match(r'(?is)^(\s*)INSERT\s+OR\s+IGNORE\s+INTO\b', sql)
    if ignore:
        sql = sql[:ignore.start()] + ignore.group(1) + 'INSERT INTO' + sql[ignore.end():]
        ending = re.search(r'\s*;\s*$', sql)
        if ending:
            sql = sql[:ending.start()] + ' ON CONFLICT DO NOTHING' + sql[ending.start():]
        else:
            sql += ' ON CONFLICT DO NOTHING'

    chunks_query = bool(re.search(r'\bchunks\b', sql, flags=re.IGNORECASE))
    output: list[str] = []
    position = 0
    state = 'sql'
    while position < len(sql):
        char = sql[position]
        next_char = sql[position + 1] if position + 1 < len(sql) else ''
        if state == 'sql':
            if char == "'":
                state = 'single'
            elif char == '"':
                state = 'double'
            elif char == '-' and next_char == '-':
                state = 'line_comment'
            elif char == '/' and next_char == '*':
                state = 'block_comment'
            elif char == '?':
                output.append('%s')
                position += 1
                continue
            elif (chunks_query and sql[position:position + 6].lower() == 'offset'
                  and (position == 0 or not (sql[position - 1].isalnum() or sql[position - 1] == '_'))
                  and (position + 6 == len(sql) or not (
                      sql[position + 6].isalnum() or sql[position + 6] == '_'))):
                output.append('"offset"')
                position += 6
                continue
        elif state == 'single' and char == "'":
            if next_char == "'":
                output.extend((char, next_char))
                position += 2
                continue
            state = 'sql'
        elif state == 'double' and char == '"':
            if next_char == '"':
                output.extend((char, next_char))
                position += 2
                continue
            state = 'sql'
        elif state == 'line_comment' and char == '\n':
            state = 'sql'
        elif state == 'block_comment' and char == '*' and next_char == '/':
            output.extend((char, next_char))
            position += 2
            state = 'sql'
            continue
        output.append('%%' if has_parameters and char == '%' else char)
        position += 1
    return ''.join(output)


class PostgresSession(SqliteSession):
    def __init__(self, connection, *, write: bool):
        super().__init__(connection, write=write)
        self.pending_effect_ids: list[str] = []

    def execute(self, sql, parameters=(), *, write=False):
        self.check(write)
        try:
            # With an empty parameter tuple psycopg still parses literal '%' as a
            # placeholder; SQL such as LIKE 'policy:%' must be sent unchanged.
            return self._connection.execute(
                _postgres_sql(sql, has_parameters=bool(parameters)), parameters or None)
        except psycopg.errors.IntegrityError as exc:
            raise Failure("constraint_conflict") from exc
        except (psycopg.errors.DeadlockDetected, psycopg.errors.LockNotAvailable,
                psycopg.errors.QueryCanceled) as exc:
            raise Failure("server_busy", retryable=True) from exc

    async def enqueue(self, job):
        await super().enqueue(job)
        self.pending_effect_ids.append(job.id)


class PostgresMetadataStore:
    """One connection per transaction; no mutable process-local authority state."""

    def __init__(self, dsn: str, *, signal=None, initialize: bool = True):
        self.dsn = dsn
        self.signal = signal
        self._current = contextvars.ContextVar('msg_pg_transaction_' + uuid.uuid4().hex, default=None)
        if initialize:
            with self._connect() as conn:
                # Multiple daemon workers may initialize the same fresh database.
                conn.execute('SELECT pg_advisory_xact_lock(725274758, 1886265951)')
                conn.execute(_SCHEMA)

    def _connect(self):
        return psycopg.connect(self.dsn, autocommit=False)

    async def _connect_async(self):
        pending = asyncio.create_task(asyncio.to_thread(self._connect))
        try:
            return await asyncio.shield(pending)
        except asyncio.CancelledError:
            # Cancelling a coroutine does not stop a connection attempt in a thread.
            # Consume its result and close it instead of leaking a server connection.
            try:
                connection = await pending
                await asyncio.to_thread(connection.close)
            finally:
                raise

    @asynccontextmanager
    async def transaction(self, *, write):
        existing = self._current.get()
        if existing is not None:
            existing.check(write)
            name = 'nested_' + uuid.uuid4().hex
            existing.execute('SAVEPOINT ' + name)
            pending_at_entry = len(existing.pending_effect_ids)
            try:
                yield existing
                existing.execute('RELEASE SAVEPOINT ' + name)
            except BaseException:
                existing.execute('ROLLBACK TO SAVEPOINT ' + name)
                existing.execute('RELEASE SAVEPOINT ' + name)
                del existing.pending_effect_ids[pending_at_entry:]
                raise
            return

        conn = await self._connect_async()
        tx = PostgresSession(conn, write=write)
        token = None
        committed = False
        try:
            if write:
                # A fixed application-wide key serializes writers, including separate workers.
                # Waiting happens off the event loop so the holder can finish its request.
                async def acquire():
                    def blocking():
                        conn.execute("SET lock_timeout = '10s'")
                        conn.execute('SELECT pg_advisory_xact_lock(725274758, 1886265951)')
                    task = asyncio.create_task(asyncio.to_thread(blocking))
                    try:
                        await asyncio.shield(task)
                    except asyncio.CancelledError:
                        # The worker thread must finish before this connection is closed.
                        try:
                            await task
                        finally:
                            raise
                try:
                    await acquire()
                except (psycopg.errors.LockNotAvailable, psycopg.errors.QueryCanceled) as exc:
                    raise Failure('server_busy', retryable=True) from exc
            else:
                conn.execute('SET TRANSACTION READ ONLY')
            token = self._current.set(tx)
            yield tx
            conn.commit()
            committed = True
        except BaseException:
            conn.rollback()
            raise
        finally:
            tx.closed = True
            if token is not None:
                self._current.reset(token)
            conn.close()
        if committed and self.signal is not None and tx.pending_effect_ids:
            # The durable jobs table is authoritative. A signal only reduces worker latency.
            try:
                await self.signal.publish_pending(tuple(tx.pending_effect_ids))
            except Exception:
                logging.getLogger(__name__).exception('Valkey job signal failed; jobs remain durable')

    async def close(self):
        return None

    def backup(self, destination: Path):
        """Write a pg_dump custom-format archive at *destination*.

        The caller holds the store's write transaction while copying content trees.
        Credentials travel via the child environment, never command arguments.
        """
        destination = Path(destination)
        fields = conninfo_to_dict(self.dsn)
        password = fields.pop('password', None)
        env = os.environ.copy()
        if password is not None:
            env['PGPASSWORD'] = password
        safe_dsn = make_conninfo(**fields)
        subprocess.run(['pg_dump', '--format=custom', '--no-owner', '--no-acl',
                        '--file', str(destination), '--dbname', safe_dsn],
                       env=env, check=True, capture_output=True)
