from __future__ import annotations

from .models import *
from .query import QuerySession

class MetadataSession(QuerySession, Protocol):
    def on_rollback(self, effect: Callable[[], Awaitable[None]]) -> None: ...
    async def resource(self, id: ResourceId) -> Resource: ...
    async def resolve(self, path: str) -> ResourceId: ...
    async def path(self, id: ResourceId) -> str: ...
    async def ancestors(self, id: ResourceId) -> tuple[Resource, ...]: ...
    async def children(
        self, parent: ResourceId, cursor: str | None, limit: int
    ) -> Page[Resource]: ...
    async def revision(self, ref: ResourceRef) -> Revision: ...
    async def history(
        self, id: ResourceId, cursor: str | None, limit: int
    ) -> Page[Revision]: ...
    async def insert(self, resource: Resource) -> None: ...
    async def replace(
        self, resource: Resource, expected_generation: int
    ) -> None: ...
    async def append_revision(self, revision: Revision) -> None: ...
    async def subject(self, id: ResourceId) -> Subject: ...
    async def organization(self, id: ResourceId) -> Organization: ...
    async def credential(self, id: ID) -> Credential: ...
    async def certificate(self, id: ResourceId) -> Certificate: ...
    async def certificate_revoked(self, id: ResourceId) -> bool: ...
    async def memberships(
        self, subject: ResourceId
    ) -> tuple[Membership, ...]: ...
    async def request_result(
        self, subject: ResourceId, id: RequestId, digest: Digest
    ) -> OperationResult | None: ...
    async def save_result(
        self, subject: ResourceId, digest: Digest, result: OperationResult
    ) -> None: ...
    async def update_identity(
        self, record: Subject | Organization | Membership | EmailSettings,
        expected_generation: int
    ) -> None: ...
    async def save_credential(
        self, credential: Credential, expected_auth_version: int
    ) -> None: ...
    async def csr(self, id: ResourceId) -> CertificateRequest: ...
    async def csr_state(
        self, id: ResourceId
    ) -> CertificateRequestState: ...
    async def save_csr(
        self, request: CertificateRequest
    ) -> None: ...
    async def transition_csr(
        self, state: CertificateRequestState, expected_generation: int
    ) -> None: ...
    async def revoke_certificate(
        self, id: ResourceId, event: AuditEvent
    ) -> None: ...
    async def register_certificate(
        self, certificate: Certificate, csr_id: ResourceId,
        expected_generation: int
    ) -> None: ...
    async def transfer(self, id: ID) -> TransferSession: ...
    async def save_transfer(
        self, session: TransferSession, expected_generation: int | None
    ) -> None: ...
    async def put_chunk(self, chunk: TransferChunk) -> None: ...
    async def missing_ranges(
        self, id: ID, cursor: str | None, limit: int
    ) -> Page[ByteRange]: ...
    async def append_event(self, event: Event) -> None: ...
    async def append_audit(self, event: AuditEvent) -> None: ...
    async def enqueue(self, job: EffectJob) -> None: ...
    async def job(self, id: ID) -> EffectJob: ...
    async def save_job(self, job: EffectJob) -> None: ...


class MetadataStore(Protocol):
    def transaction(
        self, *, write: bool
    ) -> AbstractAsyncContextManager[MetadataSession]: ...


class ContentStore(Protocol):
    async def put(
        self, chunks: AsyncIterator[bytes], media_type: str,
        expected_digest: Digest | None = None
    ) -> BlobRef: ...
    def read(
        self, blob: BlobRef, byte_range: ByteRange | None = None
    ) -> AsyncIterator[bytes]: ...
    async def pin(self, blob: BlobRef, lease_id: ID) -> None: ...
    async def unpin(self, blob: BlobRef, lease_id: ID) -> None: ...


class Authenticator(Protocol):
    async def authenticate(
        self, request: OperationRequest, session: MetadataSession,
        *, entry: Entry
    ) -> Principal: ...


class Authorizer(Protocol):
    async def require(
        self, context: ExecutionContext, request: OperationRequest,
        checks: tuple[AccessRequirement, ...], session: MetadataSession
    ) -> tuple[ResourceRef, ...]: ...


class Signer(Protocol):
    @property
    def key_id(self) -> ID: ...
    def sign(self, payload: bytes, *, purpose: str) -> Signature: ...


class ClientTransport(Protocol):
    async def discover(self) -> TransportLimits: ...
    async def call(self, request: OperationRequest) -> OperationResult: ...


class ToolExecutor(Protocol):
    async def invoke(
        self, context: ExecutionContext, tool: ToolSpec,
        arguments: JsonMap, policy: NetworkPolicy
    ) -> ResourceRef: ...


class NotificationSender(Protocol):
    async def send(self, job: EffectJob) -> Literal['sent', 'uncertain']: ...
