[package]
name = "msg-identity"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
msg-core = { path = "../msg-core" }
msg-crypto = { path = "../msg-crypto" }
msg-protocol = { path = "../msg-protocol" }
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
subtle.workspace = true

[lints]
workspace = true
