[package]
name = "msg-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
msg-core = { path = "../msg-core" }
msg-identity = { path = "../msg-identity" }
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
msg-crypto = { path = "../msg-crypto" }

[target.'cfg(unix)'.dependencies]
fs2.workspace = true
libc.workspace = true

[dev-dependencies]
msg-protocol = { path = "../msg-protocol" }

[lints]
workspace = true
